### GET information of the pokemon 'Ditto'
GET http://localhost:1234/

### For create a new pokemon
POST http://localhost:1234/pokemon2
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]
}